export const users = [
  {
    key:1,
    login: "Diana Prince",
    email: "diana.prince@example.com",
    avatar_url: "https://cdn4.iconfinder.com/data/icons/superhero/400/wonderwoman.png",
  },
    {
    key:2,
    login: "Bruce Wayne",
    email: "bruce.wayne@example.com",
    avatar_url: "https://cdn4.iconfinder.com/data/icons/superhero/400/batman.png",
  },  
  {
    key:3,
    login: "Clark Kent",
    email: "clark.kent@example.com",
    avatar_url: "https://cdn4.iconfinder.com/data/icons/superhero/400/superman.png",
  },  
  {
    key:4,
    login: "Steve Rogers",
    email: "steve.rogers@example.com",
    avatar_url: "https://cdn4.iconfinder.com/data/icons/superhero/400/captainamerica.png",
  },

];

    // "login": "defunkt",
    // "id": 2,
    // "avatar_url": "https://avatars3.githubusercontent.com/u/2?v=3",
    // "gravatar_id": "",
    // "url": "https://api.github.com/users/defunkt",
    // "html_url": "https://github.com/defunkt",
    // "followers_url": "https://api.github.com/users/defunkt/followers",
    // "following_url": "https://api.github.com/users/defunkt/following{/other_user}",
    // "gists_url": "https://api.github.com/users/defunkt/gists{/gist_id}",
    // "starred_url": "https://api.github.com/users/defunkt/starred{/owner}{/repo}",
    // "subscriptions_url": "https://api.github.com/users/defunkt/subscriptions",
    // "organizations_url": "https://api.github.com/users/defunkt/orgs",
    // "repos_url": "https://api.github.com/users/defunkt/repos",
    // "events_url": "https://api.github.com/users/defunkt/events{/privacy}",
    // "received_events_url": "https://api.github.com/users/defunkt/received_events",
    // "type": "User",
    // "site_admin": true

  // "login": "ankittyagi",
  // "id": 2899349,
  // "avatar_url": "https://avatars3.githubusercontent.com/u/2899349?v=3",
  // "gravatar_id": "",
  // "url": "https://api.github.com/users/ankittyagi",
  // "html_url": "https://github.com/ankittyagi",
  // "followers_url": "https://api.github.com/users/ankittyagi/followers",
  // "following_url": "https://api.github.com/users/ankittyagi/following{/other_user}",
  // "gists_url": "https://api.github.com/users/ankittyagi/gists{/gist_id}",
  // "starred_url": "https://api.github.com/users/ankittyagi/starred{/owner}{/repo}",
  // "subscriptions_url": "https://api.github.com/users/ankittyagi/subscriptions",
  // "organizations_url": "https://api.github.com/users/ankittyagi/orgs",
  // "repos_url": "https://api.github.com/users/ankittyagi/repos",
  // "events_url": "https://api.github.com/users/ankittyagi/events{/privacy}",
  // "received_events_url": "https://api.github.com/users/ankittyagi/received_events",
  // "type": "User",
  // "site_admin": false,
  // "name": "Ankit Tyagi",
  // "company": null,
  // "blog": "",
  // "location": "Gurgaon, India",
  // "email": null,
  // "hireable": null,
  // "bio": null,
  // "public_repos": 19,
  // "public_gists": 0,
  // "followers": 0,
  // "following": 10,
  // "created_at": "2012-11-27T06:45:01Z",
  // "updated_at": "2017-06-14T09:25:26Z"
